spring:
  application:
    name: loans
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    
  h2:
    console:
      enabled: true
      
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    
    hibernate:
      ddl-auto: update

  config:
    import:
    #- "application_qa.yml"
    #- "application_prod.yml"
    - "optional:configserver:http://localhost:8071/"
    
  profiles:
    active:
    - "prods"

server:
  port: 8082
  
#build:
#  version: "3.0"

# loans:
#  message: "Welcome to EazyBank loans related local APIs "
#  contactDetails:
#    name: "Amaal Grega - Developer"
#    email: "amaal@eazybank.com"
#  onCallSupport:
#    - (452) 456-2176
#    - (546) 764-8934
  
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  
        
  endpoint:
    shutdown:
      enabled: true
    
    
      
  health:
    probes:
      enabled: true
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
      
  info:
    env:
      enabled: true
      
endpoints:
  shutdown:
    enabled: true
    
eureka:
  instance:
    prefer-ip-address: true
  
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/      
        
        
info:
  app:
    name: "loans"
    description: "Eazy Bank Loans Application"
    version: "1.0.0"
    
logging:
  level:
    com:
      loan: DEBUG